import { Vendedor, SituacaoVendedor, TipoPessoaVendedor } from '../../../types';
import { VendedorFormData } from '../../../schemas/vendedorSchema';

export const getInitialData = (v?: Partial<Vendedor>, empresaId?: string): VendedorFormData => ({
  id: v?.id,
  empresaId: v?.empresaId || empresaId,
  nome: v?.nome || '',
  fantasia: v?.fantasia || '',
  codigo: v?.codigo || '',
  tipoPessoa: v?.tipoPessoa || TipoPessoaVendedor.PESSOA_FISICA,
  cpfCnpj: v?.cpfCnpj || '',
  documentoIdentificacao: v?.documentoIdentificacao || '',
  pais: v?.pais || '',
  contribuinteIcms: v?.contribuinteIcms || undefined,
  inscricaoEstadual: v?.inscricaoEstadual || '',
  situacao: v?.situacao || SituacaoVendedor.ATIVO_COM_ACESSO,
  cep: v?.cep || '',
  logradouro: v?.logradouro || '',
  numero: v?.numero || '',
  complemento: v?.complemento || '',
  bairro: v?.bairro || '',
  cidade: v?.cidade || '',
  uf: v?.uf || '',
  telefone: v?.telefone || '',
  celular: v?.celular || '',
  email: v?.email || '',
  emailComunicacao: v?.emailComunicacao || '',
  depositoPadrao: v?.depositoPadrao || '',
  senha: '', // Senha nunca é carregada do backend
  acessoRestritoHorario: v?.acessoRestritoHorario || false,
  acessoRestritoIp: v?.acessoRestritoIp || '',
  perfilContato: v?.perfilContato || [],
  permissoesModulos: v?.permissoesModulos || {},
  regraLiberacaoComissao: v?.regraLiberacaoComissao || undefined,
  tipoComissao: v?.tipoComissao || undefined,
  aliquotaComissao: v?.aliquotaComissao || null,
  desconsiderarComissionamentoLinhasProduto: v?.desconsiderarComissionamentoLinhasProduto || false,
  observacoesComissao: v?.observacoesComissao || '',
  contatos: v?.contatos || [],
});
